### PR TITLE
YUP_27

### PR DESCRIPTION
**Pull request by JesseStephenBrown**
Yep. Did it again. Included a different branch (YUP_25).

Didn't even have to.

image

### CODE REVIEW

**Comment by JesseStephenBrown** [comment]
So the program compiles, but won't run correctly until the String and Letter FSAs are complete. I artificially created tokens in the dispatcher to return to test, and it did work, so HOORAY. Now we can organize proper testing of our FSAs

**Comment by brianpmaher** [comment]
+1; looks good man! on a roll!

**Comment by JesseStephenBrown** [comment]
Will conflict with sean/letterFSA, but conflicts are teensy. Remove the return null from scanner and keep Sean's stuff, and remove my constant for letters as they are defined the same anyway. Should not hold up merging this, since Sean's still needs work and these are all done.

**Comment by seanrogers2657** [comment]
Looks good. +1 
I was going to include flags for the program to run off of when the program executes so I might change how this is laid out after its merged.

**Pull request merged**
