### PR TITLE
YUP_25 - FSAs need to return Tokens with the start column, not the global column

### PR DESCRIPTION
**Pull request by JesseStephenBrown**
Should be mergeable after token refactor

### CODE REVIEW

**Comment by seanrogers2657** [comment]
Can you include my FSA in this change? :D

**Comment by brianpmaher** [comment]
+1 just merge after @seanrogers2657 CR; I think it would be easier for him to merge in his changes and change to Token instead.

**Comment by JesseStephenBrown** [comment]
This PR does not conflict with Sean's branch (checked out the latest commit on this branch, pulled in sean's current branch). YUP_27 might, but it may only conflict on the one line in constants, and maybe the line in scanner where I change int to Token.

**Comment by seanrogers2657** [comment]
+1

**Pull request merged**
