### PR TITLE
Implement string FSA

### PR DESCRIPTION
**Pull request by JesseStephenBrown**
Strings are weird, because in µPascal, ' opens a string, ' closes that string, but '''hello world''' is the string <'hello world'> where the ' are actually the single quote character. Yes, two single quotes escapes to one quote. Fun! Note we also don't include the opening/closing apostrophe in the lexeme, see: http://hypertextbookshop.com/transPL/Contents/03_Milestones/03_Milestone_3_-_Scanner_II.html

So the DFA goes S0-----'----->S1-----'----->(S2)----'---->S1

S3 is the optionally many character state, and only non-accepts EOL. Single apostrophe from S3 closes the string at S2, unless there are more apostrophes following. S1 goes to S3 at any non-EOL, non-Apostrophe, and S3 loops until an apostrophe is reached.

Oh, and errors from EOL characters are RUN_STRING, because they are runaway strings.

### CODE REVIEW

**Comment by brianpmaher** [comment]
I'll review this today; just want to follow along making my own FSA

**Comment by brianpmaher** [comment]
VVV Sean has a point. What if we want to print an apostrophe like the actual string containing only a single quote. ''' => '' which this FSA appears to handle; where what we actually mean is '''' = '''?

**Comment by seanrogers2657** [comment]
Are we including the ''' to be considered strings? Example: String apostrophe = '''; 

As far as I can tell, if given this then the machine will be stuck in s1 and error.

**Comment by brianpmaher** [comment]
Nice catch @seanrogers2657

**Comment by brianpmaher** [comment]
You'll need to merge this with master as well... I merged all CRed PRs today.

**Comment by JesseStephenBrown** [comment]
You are going to have to be more descriptive with your problem of this, because '''''''''''''' gets confusing.

**Comment by brianpmaher** [comment]
Sorry, I'll clarify (and feel free to correct me if I'm wrong): for clarity I will use the following notation: the left side is what uPascal sees, the right side of the => is what C# sees, the top example is just an example to reiterate;

```
// uPascal => C#
' string ' => " string "
// below shows an unescaped string
' string '' => " string \'
' ''string'' ' => " \'string\' "
' '' ' => " \' "
```

**Comment by brianpmaher** [comment]
I believe your FSA allows for three single quotes, this is an issue.

**Comment by JesseStephenBrown** [comment]
So you mean you believe my FSA allows for:

''' => something valid?

**Comment by JesseStephenBrown** [comment]
I've run through it, double check it if you still think it does it incorrectly, but it seems that if you have a string of three single quotes in pascal, then you end up continuing the parse of the string (unless you get a newline, but that's a string runaway error). So in pascal => C#

'''           some other text \n => run string error
'''           some test' => '          some test
'''           some test''' => '          some test'

**Comment by JesseStephenBrown** [comment]
On that note, we may want to consider specifications on when we are to continue scanning (end of line, end of token, etc. and if we want to treat different errors differently).

**Comment by JesseStephenBrown** [comment]
Contents of digiterror.mp:

```
0123456789
'''
```

Results from running:

```
jessebrown:~/workspaces/pers/uPascal-Compiler (test)$ mono Yµp.exe testProgs/digiterror.mp
TOKEN           LINE  COLUMN    LEXEME
INTEGER_LIT        1       1    0123456789
RUN_STRING         2       0    '
```

Notice that it takes ''' as RUN_STRING, but still gives us the lexeme (useful for error messaging)

**Comment by brianpmaher** [comment]
Ok, I understand now. +1

**Comment by brianpmaher** [comment]
:+1:

**Comment by seanrogers2657** [comment]
+1
:accept:

**Pull request merged**
