### PR TITLE
DO NOT MERGE WIP - B level part1

### PR DESCRIPTION
**Pull request by JesseStephenBrown**
This diff will be weird until Symbols are merged, and this PR will have to merge deconflict post-linting. Still, repeats work with this pr, and some of lab10 is done (almost all of it, but we might need to think hard about whether or not the output will look like this or not.)

### CODE REVIEW

**Comment by JesseStephenBrown** [comment]
Y'all should be careful and not overwrite each other's shiz. According to the diff, while was done -ish around aaff70e, but now only shows label generation.

**Comment by JesseStephenBrown** [comment]
Oh nevermind, I see what's going on. So if/else and repeat is done, while is being reworked, and for is remaining also?

**Comment by seanrogers2657** [comment]
Oh. While was supposed to be done as well. How is it overwriting?

Edit: Nevermind. I have branch with the while loop being complete. Just have to merge it with this branch.

**Comment by seanrogers2657** [comment]
+1

**Comment by brianpmaher** [comment]
+1

**Pull request merged**
