### PR TITLE
Tabs to spaces

### PR DESCRIPTION
**Pull request by JesseStephenBrown**
https://github.com/bmaher91/uPascal-Compiler/pull/7 Is a dependency, do not merge until https://github.com/bmaher91/uPascal-Compiler/pull/7 has been merged. His changes will also show up here until the merge has happened, so if you see things that are not tabs-to-spaces, then https://github.com/bmaher91/uPascal-Compiler/pull/7 has not yet been merged.

Has https://github.com/bmaher91/uPascal-Compiler/pull/7 been merged? Go ahead and merge this branch, as long as https://github.com/bmaher91/uPascal-Compiler/pull/7 has been merged.

### CODE REVIEW

**Comment by brianpmaher** [comment]
+1 once #7 is merged.

**Comment by seanrogers2657** [comment]
+1

**Comment by JesseStephenBrown** [comment]
Nooooooooooooooooooooo. Fixing.

**Comment by brianpmaher** [comment]
I don't think this is even necessary anymore, I included this fix in #7

**Comment by JesseStephenBrown** [comment]
When you changed the for loop, you went back to tabbing. One second, new commit will be up

**Comment by brianpmaher** [comment]
Oh really? Ok, thanks. I'll make sure I keep it all consistent.

**Comment by JesseStephenBrown** [comment]
Preserved your for loop changes, but tab->spaced it

**Comment by brianpmaher** [comment]
Looks good, +1 again. We should add a .editor file ticket to SD

**Comment by JesseStephenBrown** [comment]
Handled by https://github.com/bmaher91/uPascal-Compiler/pull/9

I will delete this branch once #9 is merged

**Pull request closed without merging**
