### PR TITLE
Reset column with curByte

### PR DESCRIPTION
**Pull request by JesseStephenBrown**
Woohoo. A pull request that can be merged without any dependencies.

### CODE REVIEW

**Comment by brianpmaher** [comment]
+1, long read. Try to keep these PRs shorter.

**Comment by seanrogers2657** [comment]
+1

**Comment by JesseStephenBrown** [comment]
Merge conflicts? FFFFfUUUUuuu

**Comment by JesseStephenBrown** [comment]
Need one +1 and then merge it.

**Comment by JesseStephenBrown** [comment]
Just trolling, I forgot to Ctrl+S.

**Comment by brianpmaher** [comment]
I see the merge conflicts are still in code.. am I missing something?

**Comment by brianpmaher** [comment]
merge this +1

**Pull request merged**
